### ISSUE TITLE
Modded Game crashes after title scene with Simplified Chinese Translation

### ISSUE THREAD

**Issue by Tanimodori** [probable-basilisk/noitajunk#1]
Last few lines in `logger.txt` is

```
LUA: Initialized random weather	
LUA: Wow the mod loaded?	
LUA: Got 74 Liquids	
LUA: Got 87 Solids	
LUA: Got 142 Sands	
LUA: Got 16 Gases	
LUA: Got 16 Fires	
LUA: Creating cheat GUI	
LUA: Starting GUI loop	
Loading 3 : 4.1126
Loading 4 : 4.11324
Loading 5: 5.76224
Loading 6: 5.76375
Loading took: 7.49453 (preload took: 1.6507)
```

Some Translations uses Unicode fonts for CJK characters, maybe there're some different displaying methods compared to English.

**Comment by probable-basilisk** [comment]
Cheatgui has moved to "https://github.com/probable-basilisk/cheatgui"; feel free to re-open this issue there; I will investigate whether the in-game GUI is capable of drawing non-ascii text.
